# Generated by Django 5.0.7 on 2024-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("num_days", models.IntegerField()),
                ("itinerary", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="average_price",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.CharField(max_length=50),
        ),
    ]
